/* Mobile/tablet shell. Course content, assessment and presentation stay separate. */
(() => {
'use strict';
const E=window.AssessmentEngine,B=window.AssessmentBank,C=window.ORAL_HEALTH_COURSE;
if(!E||!B||!C)return;
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={menu:'M4 6h16M4 12h16M4 18h16',book:'M12 5v15M12 5C8 2 4 3 2 4v15c4-2 7-1 10 1 3-2 6-3 10-1V4c-3-1-6-2-10 1Z',study:'m12 3 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z',chart:'M4 20V12M12 20V4M20 20V8',review:'M4 10a8 8 0 1 1 1 8M4 4v6h6',arrow:'m14 5-7 7 7 7',check:'m5 12 4 4L19 6',layers:'m12 3 10 5-10 5L2 8Zm-10 10 10 5 10-5M2 18l10 5 10-5'};
const icon=n=>`<svg class="symbol" viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[n]||icons.book}"/></svg>`;
$('#menuButton').innerHTML=icon('menu');document.querySelectorAll('[data-icon]').forEach(x=>x.innerHTML=icon(x.dataset.icon));
let store;try{store=localStorage;}catch{store={getItem(){throw Error()},setItem(){throw Error()}};}
const loaded=E.load(store);let state=loaded.state,protect=!!loaded.warning;
const UI_KEY='dental-mobile-v1',SETTINGS_KEY='oral-health-ui-settings-v1';
function read(key,fallback){try{return JSON.parse(store.getItem(key))||fallback;}catch{return fallback;}}
let ui=read(UI_KEY,{});if(!ui||typeof ui!=='object'||Array.isArray(ui))ui={};
ui={notes:{},ink:{},read:{},list:false,size:'normal',...ui};for(const k of ['notes','ink','read'])if(!ui[k]||typeof ui[k]!=='object'||Array.isArray(ui[k]))ui[k]={};
let settings=read(SETTINGS_KEY,{theme:'light',hideImages:false});
const units=C.modules.flatMap(m=>m.units),lessons=units.flatMap(u=>u.lessons.map(l=>({...l,unit:u}))),main=$('#appMain'),drawer=$('#settingsDrawer');
let route='',catalogPage=0,query='',unitFilter='',examIndex=0,response=null,order=[],inkOn=false,reader=null;
function notice(message){$('#saveWarning').hidden=!message;$('#saveWarning').textContent=message||'';}
if(loaded.warning)notice(loaded.warning+' يمكنك تصدير البيانات الجديدة؛ الحفظ فوق النسخة القديمة متوقف.');
function save(){if(protect)return;const r=E.save(store,state);if(!r.ok)notice(r.warning);}
function saveUI(){try{store.setItem(UI_KEY,JSON.stringify(ui));}catch{notice('تعذر حفظ الملاحظات على الجهاز. صدّر بياناتك من القائمة.');}}
function applySettings(){document.documentElement.dataset.theme=settings.theme==='dark'?'dark':'light';document.body.classList.toggle('hide-lesson-images',!!settings.hideImages);document.documentElement.style.setProperty('--reading-size',ui.size==='larger'?'1.3rem':ui.size==='large'?'1.15rem':'1rem');$('#themeToggle').setAttribute('aria-pressed',settings.theme==='dark');$('#imagesToggle').setAttribute('aria-pressed',!!settings.hideImages);$('#annotationToggle').setAttribute('aria-pressed',inkOn);$('#textSize').value=ui.size;}
function saveSettings(){try{store.setItem(SETTINGS_KEY,JSON.stringify(settings));}catch{notice('تعذر حفظ إعدادات العرض.');}applySettings();}
function go(hash){if(location.hash==='#'+hash)render();else location.hash=hash;}
function openDrawer(){drawer.showModal();$('#menuButton').setAttribute('aria-expanded','true');}
function closeDrawer(){drawer.close();}
$('#menuButton').onclick=openDrawer;$('#closeDrawer').onclick=closeDrawer;drawer.addEventListener('close',()=>{$('#menuButton').setAttribute('aria-expanded','false');$('#menuButton').focus();});
drawer.addEventListener('click',e=>{if(e.target===drawer&&e.clientX<drawer.getBoundingClientRect().left)closeDrawer();});
$('#themeToggle').onclick=()=>{settings.theme=settings.theme==='dark'?'light':'dark';saveSettings();};
$('#imagesToggle').onclick=()=>{settings.hideImages=!settings.hideImages;saveSettings();};
$('#textSize').onchange=e=>{ui.size=e.target.value;saveUI();applySettings();};
$('#annotationToggle').onclick=()=>{if(!reader){$('#annotationHelp').textContent='اختر درسًا من قسم الدروس أولًا، ثم فعّل الكتابة هنا.';return;}inkOn=!inkOn;applySettings();closeDrawer();renderReader(reader.lesson.id,reader.part);};
$('#closeImage').onclick=()=>$('#imageDialog').close();
$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify({format:'dental-mobile-backup-v1',exportedAt:new Date().toISOString(),assessment:state,ui,settings},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dental-study-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#importData').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>25*1024*1024)throw Error();const data=JSON.parse(await file.text());if(data.format!=='dental-mobile-backup-v1'||!E.valid(data.assessment)||!data.ui||!['notes','ink','read'].every(k=>data.ui[k]&&typeof data.ui[k]==='object'&&!Array.isArray(data.ui[k])))throw Error();if(!confirm('استبدال تقدم التدريب والملاحظات الحالية بهذه النسخة؟ صدّر النسخة الحالية أولًا إن كنت تحتاجها.'))return;store.setItem(E.KEY,JSON.stringify(data.assessment));store.setItem(UI_KEY,JSON.stringify(data.ui));if(data.settings)store.setItem(SETTINGS_KEY,JSON.stringify(data.settings));location.reload();}catch{notice('لم تُستورد النسخة. تحقق من الملف والمساحة المتاحة.');}finally{e.target.value='';}};
function tab(name){document.querySelectorAll('[data-tab]').forEach(a=>{if(a.dataset.tab===name)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});}
function openErrors(){return Object.values(state.records).filter(r=>r.open).length;}
function head(kicker,title,extra=''){return `<div class="screen-head"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1></div>${extra}</div>`;}
function coverage(){return '<p class="coverage-note">التدريب يغطي أهدافًا مختارة من المقرر؛ نتيجته لا تعني إتقان جميع تفاصيل الدرس.</p>';}
function resume(){const a=state.active;if(!a||a.finishedAt)return '';return `<section class="resume-card"><p><strong>نكمل من حيث توقفت؟</strong><br><small>${Object.keys(a.answers).length} من ${a.items.length} إجابة محفوظة</small></p><button class="primary" data-action="resume">متابعة المحاولة</button><button class="secondary" data-action="end">إنهاء المحاولة</button></section>`;}
function study(){tab('study');main.innerHTML=`<div class="screen study-screen">${resume()}<section class="study-hero"><div class="eyebrow">خطوة صغيرة، فهم أعمق</div><h1>ماذا تريد أن تدرس اليوم؟</h1><p>اختر درسًا، اختبر ما تتذكره، ثم ارجع إلى الأفكار التي تحتاج مراجعة.</p><div class="hero-line"><span>17 وحدة</span><span>93 درسًا مفتوحًا</span><span>تقدم محفوظ</span></div></section><div class="study-modes"><button class="mode-card" data-action="comprehensive"><span class="tile-icon">${icon('layers')}</span><strong>امتحان شامل</strong><p>34 سؤالًا متنوعًا من الوحدات كلها، مع اهتمام بأخطائك.</p><span class="card-link">ابدأ محاولة جديدة ←</span></button><a href="#individual" class="mode-card"><span class="tile-icon">${icon('book')}</span><strong>امتحان فردي</strong><p>اختر أي درس وتدرّب على أهدافه المتاحة. جميع الدروس مفتوحة.</p><span class="card-link">اختر الدرس ←</span></a><button class="mode-card review-card" data-action="mistakes"><span class="tile-icon">${icon('review')}</span><div><strong>مراجعة أخطائي</strong><p>${openErrors()?`${openErrors()} فكرة تحتاج إلى مراجعتك`:'تجتمع هنا الأفكار التي تحتاج مراجعة'}</p></div><span class="card-link">${openErrors()?'لنراجعها ←':'لا أخطاء بعد'}</span></button></div>${coverage()}</div>`;}
function catalog(individual=false){tab(individual?'study':'lessons');main.innerHTML=`<div class="screen">${head(individual?'الدراسة · امتحان فردي':'مكتبتك الدراسية',individual?'أي درس تريد اختباره؟':'تصفّح الدروس',individual?'<a class="secondary" href="#study">رجوع</a>':'')}<div class="catalog-tools"><input type="search" id="lessonSearch" placeholder="ابحث عن درس أو مفهوم…" aria-label="البحث في الدروس" value="${esc(query)}"><select id="unitFilter" aria-label="اختر الوحدة"><option value="">كل الوحدات · 17</option>${units.map(u=>`<option value="${u.id}" ${unitFilter===u.id?'selected':''}>${esc(u.title)}</option>`).join('')}</select><button class="icon" id="layoutToggle" aria-label="تبديل عرض قائمة وبطاقات" aria-pressed="${!!ui.list}">${icon('menu')}</button></div><div id="catalogResults"></div>${individual?coverage():''}</div>`;$('#lessonSearch').oninput=e=>{query=e.target.value;catalogPage=0;catalogResults(individual);};$('#unitFilter').onchange=e=>{unitFilter=e.target.value;catalogPage=0;catalogResults(individual);};$('#layoutToggle').onclick=()=>{ui.list=!ui.list;saveUI();$('#layoutToggle').setAttribute('aria-pressed',!!ui.list);catalogResults(individual);};catalogResults(individual);}
function catalogResults(individual){const found=lessons.filter(l=>(!unitFilter||l.unit.id===unitFilter)&&E.normalize(l.title+' '+l.unit.title+' '+l.contentHtml.replace(/<[^>]*>/g,' ')).includes(E.normalize(query))),size=innerWidth<700?6:9,pages=Math.max(1,Math.ceil(found.length/size));catalogPage=Math.min(catalogPage,pages-1);$('#catalogResults').innerHTML=`<p class="muted">${found.length} درس · ${individual?'اختر الدرس لبدء التدريب':'المحتوى الكامل متاح للقراءة'}</p><div class="lesson-grid ${ui.list?'is-list':''}">${found.slice(catalogPage*size,(catalogPage+1)*size).map(l=>{const b=B.lessons.find(x=>x.id===l.id);return `<button class="lesson-card-app" ${individual?'data-exam-lesson':'data-read-lesson'}="${l.id}"><span class="meta"><span>${esc(l.unit.title)}</span><span>${ui.read[l.id]?'✓ قرأته':String(l.unit.pageNumber).padStart(2,'0')}</span></span><strong>${esc(l.title)}</strong><span class="lesson-arrow">${individual?(b.objectiveIds.length?`${b.independentObjectiveCount} أهداف متاحة · ابدأ ←`:'قراءة المصدر · التقييم قيد المراجعة'):'افتح الدرس ←'}</span></button>`;}).join('')}</div>${!found.length?'<div class="empty">لا توجد نتائج. جرّب كلمة أخرى أو اختر كل الوحدات.</div>':''}<div class="pager"><button class="secondary" id="catalogPrev" ${catalogPage===0?'disabled':''}>السابق</button><span>${catalogPage+1} / ${pages}</span><button class="secondary" id="catalogNext" ${catalogPage+1>=pages?'disabled':''}>التالي</button></div>`;$('#catalogPrev').onclick=()=>{catalogPage--;catalogResults(individual);main.scrollTop=0;};$('#catalogNext').onclick=()=>{catalogPage++;catalogResults(individual);main.scrollTop=0;};}
function partsFor(l){const template=document.createElement('template');template.innerHTML=l.contentHtml;const parts=[...template.content.children].map(el=>el.outerHTML);return parts.length?parts:[l.contentHtml];}
function renderReader(id,part=0){const l=lessons.find(x=>x.id===id);if(!l){go('lessons');return;}tab('lessons');main.className='reader-main';const parts=partsFor(l);part=Math.min(Math.max(0,part),parts.length-1);reader={lesson:l,part,parts};ui.lastLesson=id;ui.lastPart=part;saveUI();const inkKey=id+':'+part;main.innerHTML=`<div class="reader-layout"><aside class="reader-sidebar" aria-label="دروس الوحدة"><div class="eyebrow">${esc(l.unit.title)}</div><h2>دروس الوحدة</h2>${l.unit.lessons.map(x=>`<button data-read-lesson="${x.id}" aria-current="${x.id===id}">${esc(x.title)}</button>`).join('')}</aside><section class="reader-column"><div class="reader-top"><a href="#lessons" class="icon" aria-label="العودة للدروس">${icon('arrow')}</a><div><small>${esc(l.unit.title)}</small><h1>${esc(l.title)}</h1></div></div>${inkOn?'<div class="ink-tools"><span>اكتب بالقلم أو الإصبع · حرّك الصفحة من خارج النص</span><button id="undoInk">تراجع</button><button id="stopInk">إنهاء الكتابة</button></div>':''}<div class="reader-scroll"><article class="reader-content ${inkOn?'ink-active':''}" id="lessonContent">${parts[part]}<svg class="ink-layer" id="inkLayer" viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-label="مساحة الكتابة"></svg></article><div class="notes-box"><label for="lessonNote">ملاحظاتي على الدرس</label><textarea id="lessonNote" placeholder="اكتب ملاحظة أو سؤالًا للعودة إليه…">${esc(ui.notes[id]||'')}</textarea></div></div><footer class="reader-footer"><button class="secondary" id="readerPrev" ${part===0?'disabled':''}>السابق</button><small>جزء ${part+1} / ${parts.length}</small><button class="primary" id="readerNext">${part+1<parts.length?'التالي':'أنهيت القراءة'}</button><button class="secondary" data-exam-lesson="${id}">اختبرني</button></footer></section></div>`;
$('#lessonNote').oninput=e=>{ui.notes[id]=e.target.value;saveUI();};$('#readerPrev').onclick=()=>renderReader(id,part-1);$('#readerNext').onclick=()=>{if(part+1<parts.length)renderReader(id,part+1);else{ui.read[id]=true;saveUI();go('lessons');}};
$('#lessonContent').querySelectorAll('img').forEach(img=>{img.tabIndex=0;img.setAttribute('role','button');img.setAttribute('aria-label','تكبير: '+(img.alt||'صورة الدرس'));const zoom=()=>{if(inkOn)return;$('#zoomImage').src=img.src;$('#zoomImage').alt=img.alt;$('#imageDialog').showModal();};img.onclick=zoom;img.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();zoom();}};});
const layer=$('#inkLayer');function draw(){layer.replaceChildren();for(const stroke of ui.ink[inkKey]||[]){if(!Array.isArray(stroke))continue;const path=document.createElementNS('http://www.w3.org/2000/svg','polyline');path.setAttribute('points',stroke.filter(p=>Array.isArray(p)&&p.every(Number.isFinite)).map(p=>p.join(',')).join(' '));path.setAttribute('fill','none');path.setAttribute('stroke','#d28745');path.setAttribute('stroke-width','3');path.setAttribute('vector-effect','non-scaling-stroke');path.setAttribute('stroke-linecap','round');path.setAttribute('stroke-linejoin','round');layer.append(path);}}draw();
if(inkOn){let stroke=null,pointer=null;const point=e=>{const r=layer.getBoundingClientRect();return [Math.max(0,Math.min(1000,(e.clientX-r.left)/r.width*1000)),Math.max(0,Math.min(1000,(e.clientY-r.top)/r.height*1000))];};layer.onpointerdown=e=>{if(pointer!==null)return;e.preventDefault();pointer=e.pointerId;layer.setPointerCapture(pointer);stroke=[point(e)];(ui.ink[inkKey]||=[]).push(stroke);draw();};layer.onpointermove=e=>{if(pointer!==e.pointerId||!stroke||stroke.length>=5000)return;stroke.push(point(e));draw();};const end=e=>{if(e.pointerId!==pointer)return;stroke=null;pointer=null;saveUI();};layer.onpointerup=end;layer.onpointercancel=end;$('#undoInk').onclick=()=>{ui.ink[inkKey]?.pop();saveUI();draw();};$('#stopInk').onclick=()=>{inkOn=false;applySettings();renderReader(id,part);};}
}
function begin(mode,lessonId){if(state.active&&!state.active.finishedAt){go('study');notice('لديك محاولة محفوظة. تابعها أو أنهِها قبل بدء محاولة جديدة.');return;}const a=E.select(B,state,{mode,lessonId});if(!a.items.length){main.className='';reader=null;inkOn=false;main.innerHTML=`<div class="screen">${head('الدراسة',mode==='mistakes'?'لا أخطاء للمراجعة الآن':'التقييم قيد المراجعة')}<div class="empty"><span class="tile-icon">${icon('check')}</span><p>${mode==='mistakes'?'ابدأ امتحانًا، وستجتمع هنا الأفكار التي تحتاج تدريبًا.':'هذا الدرس مفتوح للقراءة. لا نضع درجة لمحتوى لم تُعتمد له أسئلة بعد.'}</p><div class="actions"><a class="primary" href="${lessonId?'#read/'+lessonId:'#individual'}">${lessonId?'قراءة الدرس':'اختر درسًا'}</a><a class="secondary" href="#study">الدراسة</a></div></div></div>`;return;}E.start(B,state,{mode,lessonId,feedback:mode==='comprehensive'?'exam':'training'});save();examIndex=0;go('exam');}
function currentIndex(){const a=state.active;if(Number.isInteger(a.uiIndex)&&a.uiIndex>=0&&a.uiIndex<a.items.length)return a.uiIndex;const n=a.items.findIndex(q=>!a.answers[q.id]);return n<0?a.items.length-1:n;}
function questionInput(q,saved){const disabled=saved&&!saved.draft?'disabled':'';if(q.type==='choice')return `<div class="answer-options">${q.options.map((o,i)=>`<button class="answer-option" data-option="${esc(o.id)}" aria-pressed="${saved?.response===o.id}" ${disabled}><span>${i+1}</span><span>${esc(o.text)}</span></button>`).join('')}</div>`;
if(['short-answer','explanation'].includes(q.type))return `<label class="muted" for="writtenAnswer">اكتب إجابتك من الذاكرة</label><textarea id="writtenAnswer" class="written-answer" ${disabled}>${esc(saved?.response||'')}</textarea>`;
if(q.type==='matching')return q.leftOptions.map(o=>`<label class="match-row">${esc(o.text)}<select data-match="${esc(o.id)}" ${disabled}><option value="">اختر المطابقة</option>${q.rightOptions.map(r=>`<option value="${esc(r.id)}" ${saved?.response[o.id]===r.id?'selected':''}>${esc(r.text)}</option>`).join('')}</select></label>`).join('');
order=saved?.response||q.items.map(x=>x.id);return `<p class="muted">رتّب من الأعلى إلى الأسفل باستخدام السهمين.</p><div id="orderList">${orderMarkup(q,!!saved&&!saved.draft)}</div>`;}
function orderMarkup(q,disabled){return order.map((id,i)=>`<div class="order-row"><span>${esc(q.items.find(x=>x.id===id).text)}</span><button data-move="${i},-1" aria-label="تحريك العنصر ${i+1} للأعلى" ${disabled||i===0?'disabled':''}>↑</button><button data-move="${i},1" aria-label="تحريك العنصر ${i+1} للأسفل" ${disabled||i===order.length-1?'disabled':''}>↓</button></div>`).join('');}
function feedback(q,saved,a){if(a.feedback==='exam'&&!a.finishedAt)return '<div class="feedback" role="status">حُفظت إجابتك. تظهر المراجعة بعد إنهاء الامتحان.</div>';const label={correct:'إجابة صحيحة',incorrect:'لنراجع هذه الفكرة', 'needs-review':'قارن إجابتك بالنموذج'}[saved.status];return `<div class="feedback ${saved.status}" role="status"><h2>${label}</h2><p>${esc(q.explanation)}</p>${saved.status==='needs-review'?`<p class="muted">لا تُحتسب إجابتك خطأ بسبب اختلاف الصياغة. المقارنة الذاتية لا تمنح درجة آلية.</p>${saved.selfReview?'<p>سُجّلت مراجعتك الذاتية.</p>':`<div class="self-review"><button class="secondary" data-self="matches-model" data-q="${esc(q.id)}">تطابق النموذج</button><button class="secondary" data-self="uncertain" data-q="${esc(q.id)}">غير متأكد</button><button class="secondary" data-self="incorrect" data-q="${esc(q.id)}">تحتاج مراجعة</button></div>`}`:''}<details><summary>المصدر · صفحة ${q.source.pdfPage}</summary><p>${esc(q.source.excerpt)}</p><a href="source/course.pdf#page=${q.source.pdfPage}" target="_blank" rel="noopener">فتح صفحة المصدر (PDF)</a></details></div>`;}
function exam(){tab('study');const a=state.active;if(!a){go('study');return;}if(a.finishedAt){results();return;}if(examIndex<0||examIndex>=a.items.length)examIndex=0;const q=a.items[examIndex],saved=a.answers[q.id];a.uiIndex=examIndex;const draft=a.drafts?.[q.id];response=draft??null;main.className='exam-main';main.innerHTML=`<section class="exam-shell"><div class="exam-header"><button class="secondary" data-action="pause">حفظ وخروج</button><span>${a.mode==='comprehensive'?'امتحان شامل':a.mode==='mistakes'?'مراجعة الأخطاء':'امتحان الدرس'} · ${examIndex+1} / ${a.items.length}</span></div><div class="exam-progress" role="progressbar" aria-label="تقدم المحاولة" aria-valuemin="0" aria-valuemax="${a.items.length}" aria-valuenow="${Object.keys(a.answers).length}"><span style="width:${Object.keys(a.answers).length/a.items.length*100}%"></span></div><div class="question-scroll"><article class="question-card"><div class="question-kind">${esc(B.units.find(u=>u.id===q.unitId)?.title)} · ${{choice:'اختر الإجابة', 'short-answer':'استرجاع كتابي',explanation:'اشرح بفهمك',matching:'صل بين المفاهيم',ordering:'رتّب التسلسل'}[q.type]}</div><h1 id="questionTitle" tabindex="-1">${esc(q.prompt)}</h1>${questionInput(q,saved|| (draft!==undefined?{response:draft,draft:true}:null))}</article>${saved?feedback(q,saved,a):''}</div><footer class="exam-footer"><p>${a.feedback==='exam'?'التصحيح بعد إنهاء المحاولة':'خذ وقتك. الفهم أهم من السرعة.'}</p><button id="answerAction" class="primary">${saved?(examIndex+1===a.items.length?'النتيجة':'التالي'):'تأكيد الإجابة'}</button></footer></section>`;$('#answerAction').onclick=()=>{if(saved){if(examIndex+1===a.items.length){E.finish(state);save();results();}else{examIndex++;exam();}return;}let value=response;if(q.type==='short-answer'||q.type==='explanation')value=$('#writtenAnswer').value.trim();if(q.type==='matching')value=Object.fromEntries([...document.querySelectorAll('[data-match]')].map(x=>[x.dataset.match,x.value]));if(q.type==='ordering')value=order;if(value===null||value===''){notice('اكتب إجابة أو اختر خيارًا أولًا.');return;}const r=E.submit(state,q.id,value);if(r.status==='unanswered'){notice('أكمل الإجابة قبل المتابعة.');return;}if(!protect)notice('');save();exam();};}
function results(){const a=state.active;if(!a)return;tab('study');main.className='';const r=E.result(a);main.innerHTML=`<div class="screen">${head('خطوة أخرى في تعلمك','نتيجة المحاولة')}<div class="stats"><div class="stat"><strong>${r.correct}</strong><span>إجابات صحيحة</span></div><div class="stat"><strong>${r.wrong}</strong><span>تحتاج مراجعة</span></div><div class="stat"><strong>${r.pending}</strong><span>إجابات للمقارنة</span></div></div><p>${r.percentage===null?'لا توجد إجابات مصحّحة آليًا لحساب نسبة.':`النتيجة الآلية: <strong>${r.percentage}%</strong> من ${r.correct+r.wrong} إجابة مصحّحة فقط.`} ${r.unanswered?`${r.unanswered} سؤالًا دون إجابة.`:''}</p>${coverage()}<div class="actions"><button class="primary" data-action="mistakes">مراجعة أخطائي</button><a class="secondary" href="#study">العودة للدراسة</a></div><h2 style="margin-top:24px">راجع إجاباتك</h2>${a.items.map(q=>{const s=a.answers[q.id];return `<details class="review-answer"><summary>${esc(q.prompt)} · ${s?{correct:'✓',incorrect:'للمراجعة','needs-review':'للمقارنة'}[s.status]:'دون إجابة'}</summary>${s?`<p><strong>إجابتك:</strong> ${esc(responseText(q,s.response))}</p>${feedback(q,s,a)}`:`<p>${esc(q.explanation)}</p>`}</details>`;}).join('')}</div>`;}
function responseText(q,r){if(q.type==='choice')return q.options.find(x=>x.id===r)?.text||'';if(q.type==='ordering')return r.map(id=>q.items.find(x=>x.id===id)?.text).join(' ← ');if(q.type==='matching')return q.leftOptions.map(x=>x.text+': '+(q.rightOptions.find(y=>y.id===r[x.id])?.text||'')).join('؛ ');return r;}
function progress(){tab('progress');const done=state.attempts.filter(a=>a.finishedAt);main.innerHTML=`<div class="screen">${head('رحلتك مع المقرر','تقدّمك، خطوة بخطوة')}<div class="stats"><div class="stat"><strong>${Object.values(ui.read).filter(Boolean).length}</strong><span>دروس قرأتها / 93</span></div><div class="stat"><strong>${done.length}</strong><span>محاولات منتهية</span></div><div class="stat"><strong>${openErrors()}</strong><span>أفكار للمراجعة</span></div></div><p class="muted">إتمام القراءة يختلف عن إتقان المحتوى. تُراجع الأخطاء عبر محاولات متباعدة، ولا تختفي بمجرد إجابة واحدة.</p>${resume()}${ui.lastLesson?`<div class="actions"><a class="primary" href="#read/${esc(ui.lastLesson)}">متابعة آخر درس</a></div>`:''}<h2 style="margin-top:24px">المحاولات الأخيرة</h2>${done.length?done.slice(-10).reverse().map(a=>{const r=E.result(a);return `<div class="history-row"><span>${a.mode==='lesson'?esc(B.lessons.find(l=>l.id===a.lessonId)?.title||'امتحان درس'):a.mode==='comprehensive'?'امتحان شامل':'مراجعة الأخطاء'}<br><small class="muted">${new Date(a.finishedAt).toLocaleDateString('ar')}</small></span><span>${r.correct} صحيحة · ${r.wrong} خطأ<br><small class="muted">${r.pending} للمقارنة · ${r.unanswered} دون إجابة</small></span></div>`;}).join(''):'<div class="empty">ستظهر محاولاتك هنا بعد إنهائها.</div>'}<p class="coverage-note">السجل هنا خاص بالمحرك الجديد. بيانات التدريب السابقة باقية في النسخة السابقة.</p></div>`;}
main.addEventListener('click',e=>{const target=e.target.closest('button,a');if(!target)return;const d=target.dataset;if(d.readLesson){go('read/'+d.readLesson);return;}if(d.examLesson){begin('lesson',d.examLesson);return;}if(d.option!==undefined){response=d.option;saveDraft(response);document.querySelectorAll('[data-option]').forEach(x=>x.setAttribute('aria-pressed',x===target));return;}if(d.move){const [i,delta]=d.move.split(',').map(Number);[order[i],order[i+delta]]=[order[i+delta],order[i]];$('#orderList').innerHTML=orderMarkup(state.active.items[examIndex],false);saveDraft(order.slice());return;}if(d.self){E.reviewWritten(state,d.q,d.self);save();if(state.active.finishedAt){const details=target.closest('.review-answer');const q=state.active.items.find(q=>q.id===d.q);target.closest('.feedback').outerHTML=feedback(q,state.active.answers[d.q],state.active);if(details)details.open=true;}else exam();return;}switch(d.action){case 'comprehensive':begin('comprehensive');break;case 'mistakes':begin('mistakes');break;case 'resume':examIndex=currentIndex();go('exam');break;case 'pause':save();go('study');break;case 'end':if(confirm('إنهاء المحاولة الحالية؟ ستبقى إجاباتك محفوظة، والأسئلة المتبقية تُسجّل دون إجابة.')){E.finish(state);save();go('exam');}break;}});
function saveDraft(value){const a=state.active;if(!a||a.finishedAt)return;(a.drafts||={})[a.items[examIndex].id]=value;save();}
main.addEventListener('input',e=>{if(e.target.id==='writtenAnswer')saveDraft(e.target.value);});
main.addEventListener('change',e=>{if(e.target.matches('[data-match]'))saveDraft(Object.fromEntries([...document.querySelectorAll('[data-match]')].map(x=>[x.dataset.match,x.value])));});
function render(){const old=route;route=location.hash.slice(1)||'study';main.className='';if(!route.startsWith('read/')){reader=null;inkOn=false;}applySettings();if(route==='lessons')catalog(false);else if(route==='individual')catalog(true);else if(route.startsWith('read/')){const id=route.slice(5);renderReader(id,ui.lastLesson===id?ui.lastPart||0:0);}else if(route==='exam'){if(old!=='exam'&&state.active&&!state.active.finishedAt)examIndex=currentIndex();exam();}else if(route==='progress')progress();else study();if(old!==route){main.scrollTop=0;main.focus({preventScroll:true});}}
window.addEventListener('hashchange',render);applySettings();render();
})();
