const E=require('../assessment/engine.js'),B=require('../data/assessment/bank.json'),assert=require('node:assert/strict'),fs=require('node:fs');let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name)}
const now=Date.UTC(2026,9,6,10),correct=q=>q.type==='choice'?q.correctOptionId:q.type==='short-answer'?q.acceptedAnswers[0]:q.type==='ordering'?q.correctOrder:q.type==='matching'?Object.fromEntries(q.pairs.map(p=>[p.leftId,p.rightId])):q.modelAnswer;
test('All 93 lessons open; no fake certification',()=>{assert.equal(B.lessons.length,93);assert.ok(B.lessons.every(l=>l.unlocked&&!l.fullLessonCoverageCertified));assert.equal(B.lessons.filter(l=>l.coverageStatus==='source-review-only').length,1)});
test('Every source anchor and excerpt is reproducible from PDF-derived evidence',()=>{const pages=require('../data/assessment/source-pages.json').pages;for(const q of B.questions){const t=pages.find(p=>p.pdfPage===q.source.pdfPage).text;assert.equal(t.slice(q.source.anchorStart,q.source.anchorStart+q.source.anchor.length),q.source.anchor);assert.equal(t.slice(q.source.excerptStart,q.source.excerptStart+q.source.excerpt.length),q.source.excerpt)}});
test('Semantic families count objectives, not duplicated formats',()=>{assert.equal(new Set(B.objectives.map(o=>o.id)).size,181);assert.equal(new Set(B.questions.map(q=>q.id)).size,B.questions.length);assert.ok(B.questions.every(q=>B.objectives.some(o=>o.id===q.objectiveId)))});
test('All supported answer keys grade; open prose remains ungraded',()=>{for(const q of B.questions){const r=E.grade(q,correct(q));assert.equal(r.status,q.type==='explanation'?'needs-review':'correct',q.id)}});
test('Arabic spelling normalization preserves numbers and negation',()=>{assert.equal(E.normalize(' إِجابَةٌ '),E.normalize('اجابة'));assert.equal(E.normalize('٧٠٪'),E.normalize('70%'));assert.notEqual(E.normalize('0.5'),E.normalize('5'));assert.notEqual(E.normalize('لا يتراجع'),E.normalize('يتراجع'));assert.notEqual(E.normalize('-5'),E.normalize('5'))});
test('Writing uses full answer equality, not keyword acceptance',()=>{const q=B.questions.find(q=>q.type==='short-answer'&&q.acceptedAnswers.includes('العاج'));assert.equal(E.grade(q,'ليس العاج').status,'needs-review');assert.equal(E.grade(q,'جواب مرادف غير مسجل').correct,null);assert.equal(E.grade(q,'').status,'unanswered')});
test('All objective answer choices can be reshuffled without losing key',()=>{for(let i=0;i<20;i++){const a=E.select(B,E.empty(),{seed:i,count:34});for(const q of a.items.filter(q=>q.type==='choice'))assert.equal(E.grade(q,q.correctOptionId).correct,true)}});
test('Comprehensive represents all 17 units under heavy error bias',()=>{const s=E.empty();for(const o of B.objectives.filter(o=>o.unitId==='page-06'))s.records[o.id]={attempts:1,errors:50,open:true,evidence:[],due:0};const a=E.select(B,s,{seed:2,count:34});assert.equal(a.coverage.representedUnits,17);assert.ok(a.coverage.prioritySlots<=Math.floor(34*.35));assert.ok(a.items.filter(q=>q.unitId==='page-06').length<=3);assert.equal(new Set(a.items.map(q=>q.objectiveId)).size,34)});
test('Short rounds explicitly disclose incomplete unit representation',()=>{const a=E.select(B,E.empty(),{seed:3,count:5});assert.equal(a.coverage.allUnitsRepresented,false);assert.ok(a.warnings.some(w=>w.includes('مختصرة')))});
test('Lesson exam cannot leak other lessons',()=>{for(const l of B.lessons){const a=E.select(B,E.empty(),{mode:'lesson',lessonId:l.id,seed:4});assert.ok(a.items.every(q=>q.lessonIds.includes(l.id)));assert.equal(a.items.length,l.objectiveIds.length)}});
test('Disputed taste lesson stays open with source review and no fake grade',()=>{const a=E.select(B,E.empty(),{mode:'lesson',lessonId:'page-04-lesson-05'});assert.equal(a.items.length,0);assert.equal(a.heldItems.length,1);assert.equal(a.coverage.fullLessonCertified,false)});
test('Empty error review does not invent new errors',()=>{const a=E.select(B,E.empty(),{mode:'mistakes',count:10});assert.equal(a.items.length,0)});
test('All supported structured answers reject malformed submissions',()=>{for(const q of B.questions.filter(q=>['ordering','matching'].includes(q.type))){assert.equal(E.grade(q,{}).status,'unanswered');if(q.type==='ordering')assert.equal(E.grade(q,[...q.correctOrder].reverse()).status,'incorrect')}});
function one(q,s,day,id){const a=E.start(B,s,{mode:'lesson',lessonId:q.lessonIds[0],seed:id,attemptId:id,now:now+day*E.DAY});a.items=[JSON.parse(JSON.stringify(q))];return a;}
const choice=B.questions.find(q=>q.type==='choice'),written=B.questions.find(q=>q.objectiveId===choice.objectiveId&&q.type==='short-answer');
test('Wrong answer creates objective-level error; repeated submit is idempotent',()=>{const s=E.empty();one(choice,s,0,'wrong');const wrong=choice.options.find(o=>o.id!==choice.correctOptionId).id;E.submit(s,choice.id,wrong,{now});E.submit(s,choice.id,choice.correctOptionId,{now});assert.equal(s.records[choice.objectiveId].errors,1);assert.equal(s.records[choice.objectiveId].attempts,1);assert.ok(s.records[choice.objectiveId].open)});
test('Seeing answer and retrying same day cannot close mistake',()=>{const s=E.empty();one(choice,s,0,'bad');E.submit(s,choice.id,choice.options.find(o=>o.id!==choice.correctOptionId).id,{now});E.finish(s,now);for(let i=0;i<10;i++){one(written,s,0,'retry'+i);E.submit(s,written.id,correct(written),{now:now+i*1000});E.finish(s,now)}assert.ok(s.records[choice.objectiveId].open);assert.equal(s.records[choice.objectiveId].evidence.length,0)});
test('Spaced independent evidence resolves error and recurrence reopens it',()=>{const s=E.empty();one(choice,s,0,'e0');E.submit(s,choice.id,choice.options.find(o=>o.id!==choice.correctOptionId).id,{now});E.finish(s);for(const [day,q] of [[1,choice],[2,written]]){one(q,s,day,'d'+day);E.submit(s,q.id,correct(q),{now:now+day*E.DAY});E.finish(s)}assert.equal(s.records[choice.objectiveId].open,false);one(choice,s,3,'again');E.submit(s,choice.id,choice.options.find(o=>o.id!==choice.correctOptionId).id,{now:now+3*E.DAY});assert.equal(s.records[choice.objectiveId].open,true)});
test('Hints and self ratings do not supply mastery evidence',()=>{const s=E.empty();one(written,s,0,'hint');E.submit(s,written.id,correct(written),{hint:true,now});assert.equal(s.records[written.objectiveId].evidence.length,0)});
test('Written self review can queue work but cannot grant objective credit',()=>{const q=B.questions.find(q=>q.type==='explanation'),s=E.empty();one(q,s,0,'open');E.submit(s,q.id,'محاولة',{now});E.reviewWritten(s,q.id,'incorrect',now);assert.ok(s.records[q.objectiveId].open);assert.equal(E.result(s.active).correct,0);assert.equal(E.result(s.active).pending,1)});
test('Exam mode suppresses immediate feedback until submission',()=>{const s=E.empty();const a=one(choice,s,0,'exam');a.feedback='exam';E.submit(s,choice.id,correct(choice),{now});assert.deepEqual(E.publicFeedback(a,choice.id),{status:'recorded'});E.finish(s,now);assert.ok(E.publicFeedback(a,choice.id).source)});
test('New attempts vary question sequence; no duplicate objectives',()=>{const s=E.empty(),a=E.start(B,s,{seed:'same',count:34,attemptId:'a'});E.finish(s);const b=E.start(B,s,{seed:'same',count:34,attemptId:'b'});assert.notDeepEqual(a.items.map(q=>q.id),b.items.map(q=>q.id));assert.equal(new Set(b.items.map(q=>q.objectiveId)).size,b.items.length)});
test('Mistake practice chooses other available format and only open goals',()=>{const s=E.empty();one(choice,s,0,'bad2');E.submit(s,choice.id,choice.options.find(o=>o.id!=='0').id,{now});E.finish(s);const a=E.select(B,s,{mode:'mistakes',count:10,seed:8});assert.equal(a.items.length,1);assert.equal(a.items[0].objectiveId,choice.objectiveId);assert.notEqual(a.items[0].id,choice.id)});
test('Resume preserves question order, answers and source snapshots',()=>{const s=E.empty();one(choice,s,0,'save');E.submit(s,choice.id,correct(choice),{now});let raw;assert.ok(E.save({setItem:(k,v)=>raw=v},s).ok);const loaded=E.load({getItem:()=>raw});assert.deepEqual(loaded.state,s);assert.equal(loaded.state.active,loaded.state.attempts[0])});
test('Corrupt or denied storage does not overwrite existing data',()=>{assert.ok(E.load({getItem:()=>'{bad'}).warning);assert.ok(E.load({getItem:()=>JSON.stringify({schemaVersion:1,records:{x:{}},attempts:[]})}).warning);assert.equal(E.save({setItem:()=>{throw Error()}},E.empty()).ok,false)});
console.log(JSON.stringify({passed,bankVersion:B.version,objectives:B.objectives.length,variants:B.questions.length}));
