/* Integration tests: run with NODE_PATH pointing to Playwright and CHROMIUM_PATH. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),fs=require('node:fs');
(async()=>{const server=spawn('python3',['-m','http.server','8013'],{stdio:'ignore'});let browser;const report={layouts:[],flows:[],errors:[]};try{await new Promise(r=>setTimeout(r,500));browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/tmp/dental-chromium/chromium',headless:true,args:['--no-sandbox','--disable-gpu']});
const base='http://127.0.0.1:8013/site/index.html';
for(const [w,h] of [[320,568],[360,800],[390,844],[800,1280],[1280,800],[1440,900]]){
 const ctx=await browser.newContext({viewport:{width:w,height:h},serviceWorkers:'block'}),p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(base);await p.evaluate(()=>document.fonts.ready);
 async function layout(name){const x=await p.evaluate(()=>({width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth,bodyOverflow:document.body.scrollWidth>innerWidth,nav:document.querySelector('.bottom-nav').getBoundingClientRect().bottom,main:document.querySelector('#appMain').getBoundingClientRect().bottom}));assert.ok(!x.overflow&&!x.bodyOverflow,`${w} ${name} overflow`);assert.ok(x.nav<=h+1);report.layouts.push({w,h,name,...x});}
 await layout('study');if(w===390)await p.screenshot({path:'/tmp/dental-phase2-mobile.png'});
 await p.click('[data-tab=lessons]');await p.waitForSelector('[data-read-lesson]');await layout('catalog');await p.fill('#lessonSearch','الفك العلوي');assert.ok(await p.locator('[data-read-lesson]').count());await p.locator('[data-read-lesson]').first().click();await p.waitForSelector('#lessonContent');await layout('reader');await p.fill('#lessonNote','ملاحظة اختبار');
 await p.click('#menuButton');await p.click('#themeToggle');await p.selectOption('#textSize','larger');await p.click('#closeDrawer');await layout('reader-large-dark');if(w===800)await p.screenshot({path:'/tmp/dental-phase2-tablet.png'});
 await p.reload();await p.waitForSelector('#lessonNote');assert.equal(await p.inputValue('#lessonNote'),'ملاحظة اختبار');await p.click('#menuButton');await p.click('#annotationToggle');await p.waitForSelector('.ink-active');const rect=await p.locator('#inkLayer').boundingBox();await p.mouse.move(rect.x+30,rect.y+30);await p.mouse.down();await p.mouse.move(rect.x+80,rect.y+70);await p.mouse.up();assert.equal(await p.locator('#inkLayer polyline').count(),1);await p.click('#stopInk');await p.reload();assert.equal(await p.locator('#inkLayer polyline').count(),1);
 await p.click('[data-exam-lesson]');await p.waitForSelector('#answerAction');await layout('question');const type=await p.evaluate(()=>JSON.parse(localStorage.getItem(AssessmentEngine.KEY)).active.items[0].type);if(type==='choice')await p.locator('[data-option]').first().click();else await p.fill('#writtenAnswer','صياغة للمراجعة');await p.click('#answerAction');await layout('feedback');await p.click('[data-action=pause]');await p.reload();await p.click('[data-action=resume]');await p.waitForSelector('#answerAction');assert.ok(await p.evaluate(()=>Object.keys(JSON.parse(localStorage.getItem(AssessmentEngine.KEY)).active.answers).length===1));await ctx.close();
}
// Seed only the attempt selection to exercise every rendering type with real bank objects.
const ctx=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(base);
await p.evaluate(()=>{const E=AssessmentEngine,B=AssessmentBank,s=E.empty();const a=E.start(B,s,{mode:'comprehensive',attemptId:'ui-all-types'});a.feedback='training';a.items=['choice','short-answer','explanation','matching','ordering'].map(t=>B.questions.find(q=>q.type===t));E.save(localStorage,s);});await p.goto(base+'?types=1#exam');
for(let i=0;i<5;i++){
 const q=await p.evaluate(i=>JSON.parse(localStorage.getItem(AssessmentEngine.KEY)).active.items[i],i);
 if(q.type==='choice'){const wrong=q.options.find(o=>o.id!==q.correctOptionId).id;await p.click(`[data-option="${wrong}"]`);await p.reload();assert.equal(await p.locator(`[data-option="${wrong}"]`).getAttribute('aria-pressed'),'true');}
 if(q.type==='short-answer')await p.fill('#writtenAnswer',q.acceptedAnswers[0]);
 if(q.type==='explanation')await p.fill('#writtenAnswer','إجابة ذاتية');
 if(q.type==='matching')for(const pair of q.pairs)await p.selectOption(`[data-match="${pair.leftId}"]`,pair.rightId);
 if(q.type==='ordering')for(let at=0;at<q.correctOrder.length;at++){let pos=q.items.map(x=>x.id).indexOf(q.correctOrder[at]);while(pos>at){await p.click(`[data-move="${pos},-1"]`);[q.items[pos],q.items[pos-1]]=[q.items[pos-1],q.items[pos]];pos--;}}
 await p.click('#answerAction');if(q.type==='explanation')await p.click('[data-self=uncertain]');await p.click('#answerAction');
}
assert.match(await p.locator('h1').innerText(),/نتيجة/);const result=await p.evaluate(()=>{const s=JSON.parse(localStorage.getItem(AssessmentEngine.KEY));return AssessmentEngine.result(s.active)});assert.equal(result.wrong,1);assert.equal(result.correct,3);assert.equal(result.pending,1);report.flows.push('all five activity types, objective scoring and pending written self-review');
await p.click('[data-action=mistakes]');await p.waitForSelector('#answerAction');assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem(AssessmentEngine.KEY)).active.mode),'mistakes');report.flows.push('mistakes queued and new review starts');
await p.click('[data-action=pause]');p.once('dialog',d=>d.accept());await p.click('[data-action=end]');await p.click('a[href="#study"]');await p.click('[data-action=comprehensive]');await p.waitForSelector('#answerAction');const q=await p.evaluate(()=>JSON.parse(localStorage.getItem(AssessmentEngine.KEY)).active.items[0]);if(q.type==='choice')await p.click(`[data-option="${q.correctOptionId}"]`);else await p.fill('#writtenAnswer','إجابة');await p.click('#answerAction');assert.equal(await p.locator('.feedback details').count(),0);report.flows.push('comprehensive answer explanation hidden until completion');
report.flows.push('unconfirmed answer draft survives reload');
const offline=await browser.newContext({viewport:{width:390,height:844}}),op=await offline.newPage();await op.goto(base);await op.evaluate(async()=>{const reg=await navigator.serviceWorker.ready;await new Promise((resolve,reject)=>{const ch=new MessageChannel();ch.port1.onmessage=({data})=>{if(data.type==='PROGRESS')return;ch.port1.close();data.ok?resolve():reject(Error('offline download failed'));};reg.active.postMessage({type:'DOWNLOAD'},[ch.port2]);});});await offline.setOffline(true);await op.reload();await op.waitForSelector('[data-action=comprehensive]');await op.click('[data-action=comprehensive]');await op.waitForSelector('#answerAction');report.flows.push('real service worker full download and offline reload/exam');await offline.close();
assert.deepEqual(report.errors,[]);fs.writeFileSync('site/docs/phase2/browser-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify({layouts:report.layouts.length,flows:report.flows,errors:report.errors}));
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
