const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto'),E=require('../assessment/engine.js'),base=require('../data/assessment/bank.json'),W=require('../data/assessment/written-bank.json');
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../course-path-data.js'),'utf8'),ctx);const lessons=ctx.window.ORAL_HEALTH_COURSE.modules.flatMap(m=>m.units.flatMap(u=>u.lessons));
const B={...base,version:W.version,objectives:[...base.objectives,...W.objectives],questions:[...base.questions,...W.questions]};
assert.equal(W.questions.length,177);assert.equal(W.questions.filter(q=>q.type==='explanation').length,118);assert.equal(new Set(W.questions.flatMap(q=>q.lessonIds)).size,92);
assert.ok(!W.questions.some(q=>q.lessonIds.includes('page-04-lesson-05')));assert.equal(new Set(W.questions.map(q=>q.id)).size,177);
for(const q of W.questions){assert.ok(q.rubric.length);assert.equal(q.source.kind,'anchored-course-lesson');for(const e of q.source.evidence){const l=lessons.find(l=>l.id===e.lessonId);assert.ok(l);assert.equal(crypto.createHash('sha256').update(l.contentHtml).digest('hex'),e.contentSha256);}if(q.type==='explanation'){assert.equal(E.grade(q,q.modelAnswer).status,'needs-review');assert.equal(E.grade(q,'لا '+q.modelAnswer).correct,null);}}
const written={...B,questions:W.questions};for(let seed=0;seed<20;seed++){const a=E.select(written,E.empty(),{mode:'comprehensive',seed,count:34});assert.equal(a.coverage.representedUnits,17);assert.ok(a.items.every(q=>q.collection==='written'));assert.equal(new Set(a.items.map(q=>q.objectiveId)).size,34);}
for(const l of base.lessons){const a=E.select(written,E.empty(),{mode:'lesson',lessonId:l.id});assert.ok(a.items.every(q=>q.lessonIds.includes(l.id)));if(l.id!=='page-04-lesson-05')assert.ok(a.items.length);}
const q=W.questions.find(q=>q.type==='explanation'),s=E.empty();const a=E.start(written,s,{mode:'lesson',lessonId:q.lessonIds[0]});a.items=[q];E.submit(s,q.id,'إجابة تحتاج مراجعة');E.reviewWritten(s,q.id,'uncertain');assert.ok(s.records[q.objectiveId].open);E.finish(s);const next=E.start(written,s,{mode:'lesson',lessonId:q.lessonIds[0]});next.items=[q];E.submit(s,q.id,q.modelAnswer);E.reviewWritten(s,q.id,'matches-model');assert.throws(()=>E.archiveWrittenReview(s,q.id));next.answers[q.id].rubricReview=Object.fromEntries(q.rubric.map(r=>[r.id,true]));E.archiveWrittenReview(s,q.id);assert.equal(s.records[q.objectiveId].open,false);assert.equal(s.records[q.objectiveId].evidence.length,0);assert.equal(E.result(next).correct,0);assert.equal(E.result(next).pending,1);assert.ok(E.valid(s));
console.log('PASS: 177 tasks, 118 extended responses, 92 lessons, source hashes, no keyword grading, all 17 units in written exams, lesson isolation, explicit self-archive without objective credit');
