(()=>{'use strict';
const file=location.pathname.split('/').pop()||'index.html',main=document.querySelector('main');if(!main)return;
const home=['index.html','home.html','review.html'].includes(file),lesson=file==='lesson.html',ref=file.match(/^page-(\d+)\.html$/);
if(home&&window.AdaptiveBank&&window.AdaptiveEngine){let loaded;try{loaded=AdaptiveEngine.load(localStorage);}catch(_){loaded={state:AdaptiveEngine.empty(),warning:'تعذر قراءة التخزين'};}
 const s=AdaptiveEngine.stats(AdaptiveBank,loaded.state),section=document.createElement('section');section.className='learn-card learn-hero adaptive-home-entry';section.setAttribute('aria-label','مراجعة اليوم');
 section.innerHTML=`<div><span class="learn-kicker">مراجعة اليوم</span><h2>ثبّت معرفتك خطوة بخطوة</h2><p>${s.due} مستحقة · ${s.mistakes} مفاهيم تحتاج تثبيتًا · ${s.mastered}/${s.count} متقن</p><small>إكمال الدروس محفوظ في المسار؛ الإتقان يقاس بالإجابات والمراجعات.</small></div><a class="learn-primary" href="adaptive.html">${loaded.state.session&&!loaded.state.session.done?'متابعة جلستي':'ابدأ مراجعة اليوم'}</a>`;main.prepend(section);}
if(lesson){const params=new URLSearchParams(location.search),link=document.createElement('a');link.href='adaptive.html?'+new URLSearchParams({unit:params.get('unit')||'',lesson:params.get('lesson')||''});link.className='learn-source adaptive-lesson-link';link.textContent='تدريب متكيّف لهذا الدرس ↗';main.prepend(link);}
if(file==='learning-map.html'){const a=document.createElement('a');a.href='adaptive.html';a.className='learn-primary';a.style.marginBottom='18px';a.textContent='مراجعة اليوم والتدريب المتكيّف';main.prepend(a);}
const notices={6:'تنبيه علمي: تدابير تخفيف ألم التسنين الدوائية بالمقرر تحتاج مراجعة. التدريب الجديد لا يقدمها كوصفات للرضع.',4:'تنبيه موثق: خريطة توزيع المذاقات في المقرر تحتاج تصحيحًا علميًا؛ لا يُحصر كل مذاق في منطقة منفصلة. راجع تقرير المراجعة العلمية.',7:'صححنا نقل سماكة الميناء في الميزاب إلى 0.5 مم. وصف ألياف تومز وصلابة الميناء بالمقرر يحتاج مراجعة علمية؛ لا يُستخدم في التدريب المتكيف.',10:'تحتاج توصيات المعالجة وتمارين الفتح القسري وتفسير الصرير إلى مراجعة بشرية قبل اعتمادها سريريًا.',11:'صُحح عنوان القسم إلى «القلحي» وفق صفحة PDF 35، واسم المعدن إلى «البزموت» وفق PDF 37.',12:'تحتاج توصيات علاج القلاع ووصف الندبات في المقرر إلى مراجعة علمية؛ التدريب الجديد لا يقدم وصفات علاجية.',13:'النسب وأسباب الأورام تحتاج مراجعة حديثة. وصف الآفة أو صورتها لا يكفي للتشخيص. صُحح نقل نسبة سرطان اللثة إلى 10–12% بحسب PDF 46.',15:'توجد مخالفة بين المقرر والنسخة السابقة حول رائحة الفم صباحًا، وتوصية بحقن الغلوكوز تحتاج مراجعة. لم ندخلهما في التدريب المتكيف.',16:'تحتاج نسبة مص الإصبع إلى نقص حنان الأم إلى مراجعة؛ التدريب الجديد يركز على الوضعية والمدة والتكرار.',17:'توجد توصيات قديمة ومعلومات تحتاج مراجعة، منها استعمال الزرنيخ لإماتة اللب؛ هذه التوصيات غير معتمدة في التدريب الجديد.'};
if(['comprehensive-exam.html','review.html'].includes(file)){const notice=document.createElement('aside');notice.className='learn-warning';notice.textContent='هذا القسم يحتفظ بالبنك السابق؛ لم يحصل على اعتماد علمي شامل. التدريب المتكيّف يستخدم بنكًا مستقلًا موثقًا. راجع تقرير المراجعة العلمية.';main.prepend(notice);}
const n=ref?Number(ref[1]):lesson?Number(new URLSearchParams(location.search).get('unit')?.split('-')[1]):0;
if(notices[n]){const note=document.createElement('aside');note.className='learn-warning academic-notice';note.textContent=notices[n];const a=document.createElement('a');a.href='docs/SCIENTIFIC_REVIEW_AR.md';a.textContent=' تقرير المراجعة العلمية';note.append(a);main.prepend(note);}
})();
